### ISSUE TITLE
nGUI compatibility package does not work on recent nGUI version

### ISSUE THREAD

**Issue by hassy84** [imkira/unity-sysfont#8]
Using nGUI2.5.1 / Unity3.5.7 with Sysfont.

nGUI compatibility package does not work on nGUI2.5.1 due to following error. Greatly appreciated if you can create patch new nGUI version.

Assets/SysFont/Compatibility/NGUI/Editor/UISysFontLabelEditor.cs(32,27): error CS0115: `UISysFontLabelEditor.OnDrawProperties()' is marked as an override but no suitable method found to override

**Comment by imkira** [comment]
Sorry for the huge delay.

I have just updated the NGUI compatibility package to work with the latest version (2.6.1d). Download it [here](http://dl.bintray.com/content/imkira/unity-sysfont/unity3x-ngui/unity-sysfont-ngui-1_0_3.unitypackage?direct). 
Please let me know if it works with 2.5.1 too. If not, please consider updating.

**Comment by hassy84** [comment]
magnificent ! it works at nGUI2.5.1 as well.
